image:
  file: .gitpod.dockerfile

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
    onOpen: ignore
  - port: 8025
    onOpen: ignore
  - port: 1025
    onOpen: ignore
  - port: 9000
    onOpen: ignore

tasks:
  - init: gp await-port 3306 && wp-setup-plugin # or wp-setup-theme
    command: apache2ctl start # start Apache server